spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tabletophelper
    username: tabletophelper
    password: tabletophelper
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

logging:
  level:
    com.tabletophelper: DEBUG
    org.hibernate.SQL: DEBUG
