const SOURCE_NAMES: Record<string, string> = {
  'AAG': "Astral Adventurer's Guide",
  'AATM': 'Adventure Atlas: The Mortuary',
  'AI': 'Acquisitions Incorporated',
  'AitFR-AVT': 'Adventures in the Forgotten Realms: A Verdant Tomb',
  'AitFR-DN': 'Adventures in the Forgotten Realms: Deepest Night',
  'AitFR-FCD': 'Adventures in the Forgotten Realms: From Cyan Depths',
  'AitFR-ISF': 'Adventures in the Forgotten Realms: In Scarlet Flames',
  'AitFR-THP': 'Adventures in the Forgotten Realms: The Hidden Page',
  'AWM': 'Adventure with Muk',
  'AZfyT': 'A Zib for Your Thoughts',
  'BAM': "Boo's Astral Menagerie",
  'BGDIA': "Baldur's Gate: Descent Into Avernus",
  'BGG': 'Bigby Presents: Glory of the Giants',
  'BMT': 'The Book of Many Things',
  'CM': 'Candlekeep Mysteries',
  'CoA': 'Chains of Asmodeus',
  'CoS': 'Curse of Strahd',
  'CRCotN': 'Critical Role: Call of the Netherdeep',
  'DC': 'Essentials Kit: Divine Contention',
  'DIP': 'Essentials Kit: Dragon of Icespire Peak',
  'DitLCoT': 'Descent into the Lost Caverns of Tsojcanth',
  'DMG': "Dungeon Master's Guide",
  'DoD': 'Domains of Delight',
  'DoSI': 'Dragons of Stormwreck Isle',
  'DSotDQ': 'Dragonlance: Shadow of the Dragon Queen',
  'EET': 'Elemental Evil: Trinkets',
  'EGW': "Explorer's Guide to Wildemount",
  'ERLW': 'Eberron: Rising from the Last War',
  'ESK': 'Essentials Kit',
  'FTD': "Fizban's Treasury of Dragons",
  'GGR': "Guildmasters' Guide to Ravnica",
  'GoS': 'Ghosts of Saltmarsh',
  'HAT-LMI': 'Locathah My Idol',
  'HAT-TG': "Thieves' Gallery",
  'HftT': 'Hunt for the Thessalhydra',
  'HoL': 'Ravenloft: The House of Lament',
  'HotDQ': 'Hoard of the Dragon Queen',
  'IDRotF': 'Icewind Dale: Rime of the Frostmaiden',
  'IMR': 'Infernal Machine Rebuild',
  'JttRC': 'Journeys through the Radiant Citadel',
  'KftGV': 'Keys from the Golden Vault',
  'KKW': "Krenko's Way",
  'LLK': 'Lost Laboratory of Kwalish',
  'LMoP': 'Lost Mine of Phandelver',
  'LoX': 'Light of Xaryxis',
  'LR': 'Locathah Rising',
  'LRDT': "Red Dragon's Tale: A LEGO Adventure",
  'MaBJoV': "Minsc and Boo's Journal of Villainy",
  'MCV1SC': 'Monstrous Compendium Vol 1: Spelljammer',
  'MCV2DC': 'Monstrous Compendium Vol 2: Dragonlance',
  'MCV3MC': 'Monstrous Compendium Vol 3: Minecraft',
  'MCV4EC': 'Monstrous Compendium Vol 4: Eldraine',
  'MFF': "Mordenkainen's Fiendish Folio",
  'MGELFT': "Muk's Guide to Everything He Learned From Tasha",
  'MisMV1': 'Misplaced Monsters Vol 1',
  'MM': 'Monster Manual',
  'MOT': 'Mythic Odysseys of Theros',
  'MPMM': 'Mordenkainen Presents: Monsters of the Multiverse',
  'MPP': "Morte's Planar Parade",
  'MTF': "Mordenkainen's Tome of Foes",
  'NRH-ASS': 'NERDS Restoring Harmony: A Sticky Situation',
  'NRH-AT': 'NERDS Restoring Harmony: Adventure Together',
  'NRH-AVitW': 'NERDS Restoring Harmony: A Voice in the Wilderness',
  'NRH-CoI': 'NERDS Restoring Harmony: Circus of Illusion',
  'NRH-TCMC': 'NERDS Restoring Harmony: The Candy Mountain Caper',
  'NRH-TLT': 'NERDS Restoring Harmony: The Lost Tomb',
  'OGA': 'One Grung Above',
  'OotA': 'Out of the Abyss',
  'PaBTSO': 'Phandelver and Below: The Shattered Obelisk',
  'PHB': "Player's Handbook",
  'PotA': 'Princes of the Apocalypse',
  'PSA': 'Plane Shift: Amonkhet',
  'PSD': 'Plane Shift: Dominaria',
  'PSI': 'Plane Shift: Innistrad',
  'PSK': 'Plane Shift: Kaladesh',
  'PSX': 'Plane Shift: Ixalan',
  'PSZ': 'Plane Shift: Zendikar',
  'QftIS': 'Quests from the Infinite Staircase',
  'RMBRE': 'The Lost Dungeon of Rickedness: Big Rick Energy',
  'RoT': 'Rise of Tiamat',
  'RoTOS': 'Rise of Tiamat Online Supplement',
  'RtG': 'Return to the Glory',
  'SADS': 'Sapphire Anniversary Dice Set',
  'SatO': 'Sigil and the Outlands',
  'SCAG': "Sword Coast Adventurer's Guide",
  'SCC': 'Strixhaven: A Curriculum of Chaos',
  'SDW': "Essentials Kit: Sleeping Dragon's Wake",
  'SKT': "Storm King's Thunder",
  'SLW': "Essentials Kit: Storm Lord's Wrath",
  'TCE': "Tasha's Cauldron of Everything",
  'TftYP': 'Tales from the Yawning Portal',
  'ToA': 'Tomb of Annihilation',
  'ToFW': "Turn of Fortune's Wheel",
  'TTP': 'The Tortle Package',
  'VD': 'Vecna Dossier',
  'VEoR': 'Vecna: Eve of Ruin',
  'VGM': "Volo's Guide to Monsters",
  'VRGR': "Van Richten's Guide to Ravenloft",
  'WBtW': 'The Wild Beyond the Witchlight',
  'WDH': 'Waterdeep: Dragon Heist',
  'WDMM': 'Waterdeep: Dungeon of the Mad Mage',
  'XGE': "Xanathar's Guide to Everything",
  'XMtS': 'X Marks the Spot',
};

export function sourceName(abbr: string): string {
  return SOURCE_NAMES[abbr] || abbr;
}
